Sample:
 - ctrl
 - 2weeks
 - 4weeks
 - 7weeks
 - 10weeks

Histone:
 - H3K4me3
 - H3K27ac
 - H3K4me1
 - H3K27me3
 - H3K9me2
 - H3K9me3

Rep:
 - 1
 - 2
 - 3

index: /data3/leipingji/genome_index/hg38_bowtie2_index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index
hs: hs
mm: mm

