SAMPLE:
# - SRR1409975_1_5Fu_P53
 - SRR4090091_1_Nutlin3A_P53
input: SRR4090089_1_Input
index: /data3/leipingji/genome_index/hg38_bowtie2_index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index
org: hs

